version: '2.0'
services:
  challenge:
    build: .
    volumes:
      - .:/challenge-calcs/
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    command: sh -c './wait-for elasticsearch:9200 -- rspec'

  elasticsearch:
    image: elasticsearch:5.5.2
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    restart: always
    ports:
      - 9200:9200
